import type { Metadata } from "next";
import { prisma } from "@/lib/prisma";

import { SettingsForm } from "@/components/admin/settings-form";
import { toNaira } from "@/lib/money";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Settings" };

export default async function AdminSettingsPage() {
  const [settings, paystackLive, aiConfigured] = await Promise.all([
    prisma.siteSettings.findUnique({ where: { id: "singleton" } }),
    Promise.resolve(process.env.PAYSTACK_SECRET_KEY?.startsWith("sk_live") ?? false),
    Promise.resolve(Boolean(process.env.AI_API_KEY)),
  ]);

  return (
    <div className="space-y-6">
      <header>
        <h1 className="font-display text-3xl font-semibold text-royal-950">Settings</h1>
        <p className="mt-1 text-sm text-royal-900/60">
          Brand details, delivery rules, payment channels and the AI assistant.
        </p>
      </header>

      <div className="grid gap-4 md:grid-cols-3">
        <StatusCard
          label="Payments"
          ok={paystackLive}
          okText="Paystack live keys configured"
          badText="Running on test keys"
          detail={paystackLive ? "Real charges will be made." : "Payments will be simulated until live keys are set."}
        />
        <StatusCard
          label="AI follow-up assistant"
          ok={aiConfigured}
          okText="AI model connected"
          badText="Using template fallback"
          detail={
            aiConfigured
              ? "Follow-up copy is generated by the configured model."
              : "Copy is still generated from stage-aware templates, so nothing breaks without a key."
          }
        />
        <StatusCard
          label="Database"
          ok
          okText="PostgreSQL connected"
          detail={`Prisma ${process.env.NODE_ENV === "production" ? "production" : "development"} environment`}
        />
      </div>

      <section className="card p-6">
        <h2 className="font-display text-xl font-semibold text-royal-950">Site settings</h2>
        <div className="mt-6">
          <SettingsForm
            settings={{
              businessName: settings?.businessName ?? "Patience Sewing Ltd",
              tagline: settings?.tagline ?? "",
              whatsappNumber: settings?.whatsappNumber ?? "2348000000000",
              supportEmail: settings?.supportEmail ?? "hello@patiencesewing.com",
              supportPhone: settings?.supportPhone ?? "+234 800 000 0000",
              instagramHandle: settings?.instagramHandle ?? "",
              facebookUrl: settings?.facebookUrl ?? "",
              tiktokHandle: settings?.tiktokHandle ?? "",
              deliveryFee: toNaira(settings?.deliveryFee ?? 150_000),
              freeDeliveryThreshold: toNaira(settings?.freeDeliveryThreshold ?? 2_000_000),
              bankName: settings?.bankName ?? "",
              bankAccountNumber: settings?.bankAccountNumber ?? "",
              bankAccountName: settings?.bankAccountName ?? "",
              aiModel: settings?.aiModel ?? "gpt-4o-mini",
              aiEnabled: settings?.aiEnabled ?? true,
            }}
          />
        </div>
      </section>

      <section className="card p-6">
        <h2 className="font-display text-xl font-semibold text-royal-950">Environment</h2>
        <p className="mt-1.5 text-sm text-royal-900/60">
          Secrets live in <code className="rounded bg-royal-50 px-1.5 py-0.5 text-xs">.env</code> and
          are never editable from the browser. Restart the app after changing them.
        </p>
        <dl className="mt-4 grid gap-2 text-sm sm:grid-cols-2">
          {[
            ["DATABASE_URL", Boolean(process.env.DATABASE_URL)],
            ["AUTH_SECRET", Boolean(process.env.AUTH_SECRET)],
            ["PAYSTACK_SECRET_KEY", Boolean(process.env.PAYSTACK_SECRET_KEY)],
            ["PAYSTACK_WEBHOOK_SECRET", Boolean(process.env.PAYSTACK_WEBHOOK_SECRET)],
            ["NEXT_PUBLIC_WHATSAPP_NUMBER", Boolean(process.env.NEXT_PUBLIC_WHATSAPP_NUMBER)],
            ["AI_API_KEY", Boolean(process.env.AI_API_KEY)],
          ].map(([key, set]) => (
            <div key={String(key)} className="flex items-center justify-between rounded-lg bg-royal-50 px-3 py-2">
              <code className="text-xs">{key}</code>
              <span className={`status-pill ${set ? "bg-emerald-50 text-emerald-800" : "bg-red-50 text-red-700"}`}>
                {set ? "set" : "missing"}
              </span>
            </div>
          ))}
        </dl>
      </section>
    </div>
  );
}

function StatusCard({
  label,
  ok,
  okText,
  badText,
  detail,
}: {
  label: string;
  ok: boolean;
  okText: string;
  badText?: string;
  detail: string;
}) {
  return (
    <div className="card p-5">
      <p className="text-xs font-semibold uppercase tracking-wider text-royal-900/50">{label}</p>
      <p className={`mt-2 text-sm font-semibold ${ok ? "text-emerald-700" : "text-amber-700"}`}>
        {ok ? okText : (badText ?? "Not configured")}
      </p>
      <p className="mt-1 text-xs leading-relaxed text-royal-900/55">{detail}</p>
    </div>
  );
}